# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainApp_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!
from PyQt5 import QtGui
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 1220)
        MainWindow.setIconSize(QtCore.QSize(36, 36))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_7)
        self.tabWidget.setObjectName("tabWidget")
        self.vectorDataTW = QtWidgets.QWidget()
        self.vectorDataTW.setObjectName("vectorDataTW")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.vectorDataTW)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.protectedAreaBrowseTB = QtWidgets.QToolButton(self.vectorDataTW)
        self.protectedAreaBrowseTB.setObjectName("protectedAreaBrowseTB")
        self.gridLayout_5.addWidget(self.protectedAreaBrowseTB, 9, 4, 1, 1)
        self.saveRiverLE = QtWidgets.QLineEdit(self.vectorDataTW)
        self.saveRiverLE.setObjectName("saveRiverLE")
        self.gridLayout_5.addWidget(self.saveRiverLE, 6, 2, 1, 1)
        self.roadLB = QtWidgets.QLabel(self.vectorDataTW)
        self.roadLB.setObjectName("roadLB")
        self.gridLayout_5.addWidget(self.roadLB, 2, 0, 1, 1)
        self.healthFacilLB = QtWidgets.QLabel(self.vectorDataTW)
        self.healthFacilLB.setObjectName("healthFacilLB")
        self.gridLayout_5.addWidget(self.healthFacilLB, 0, 0, 1, 1)
        self.saveWaterbodyLE = QtWidgets.QLineEdit(self.vectorDataTW)
        self.saveWaterbodyLE.setObjectName("saveWaterbodyLE")
        self.gridLayout_5.addWidget(self.saveWaterbodyLE, 8, 2, 1, 1)
        self.healthFacilBrowseTB = QtWidgets.QToolButton(self.vectorDataTW)
        self.healthFacilBrowseTB.setObjectName("healthFacilBrowseTB")
        self.gridLayout_5.addWidget(self.healthFacilBrowseTB, 0, 4, 1, 1)
        self.waterbodyBrowseTB = QtWidgets.QToolButton(self.vectorDataTW)
        self.waterbodyBrowseTB.setObjectName("waterbodyBrowseTB")
        self.gridLayout_5.addWidget(self.waterbodyBrowseTB, 7, 4, 1, 1)
        self.protectedAreaLE = QtWidgets.QLineEdit(self.vectorDataTW)
        self.protectedAreaLE.setObjectName("protectedAreaLE")
        self.gridLayout_5.addWidget(self.protectedAreaLE, 9, 2, 1, 1)
        self.saveHealthFacilLE = QtWidgets.QLineEdit(self.vectorDataTW)
        self.saveHealthFacilLE.setObjectName("saveHealthFacilLE")
        self.gridLayout_5.addWidget(self.saveHealthFacilLE, 1, 2, 1, 1)
        self.saveRoadLE = QtWidgets.QLineEdit(self.vectorDataTW)
        self.saveRoadLE.setObjectName("saveRoadLE")
        self.gridLayout_5.addWidget(self.saveRoadLE, 4, 2, 1, 1)
        self.riverLB = QtWidgets.QLabel(self.vectorDataTW)
        self.riverLB.setObjectName("riverLB")
        self.gridLayout_5.addWidget(self.riverLB, 5, 0, 1, 1)
        self.protectedAreaLB = QtWidgets.QLabel(self.vectorDataTW)
        self.protectedAreaLB.setObjectName("protectedAreaLB")
        self.gridLayout_5.addWidget(self.protectedAreaLB, 9, 0, 1, 1)
        self.healthFacilLE = QtWidgets.QLineEdit(self.vectorDataTW)
        self.healthFacilLE.setObjectName("healthFacilLE")
        self.gridLayout_5.addWidget(self.healthFacilLE, 0, 2, 1, 1)
        self.riverBrowseTB = QtWidgets.QToolButton(self.vectorDataTW)
        self.riverBrowseTB.setObjectName("riverBrowseTB")
        self.gridLayout_5.addWidget(self.riverBrowseTB, 5, 4, 1, 1)
        self.watrbodyLB = QtWidgets.QLabel(self.vectorDataTW)
        self.watrbodyLB.setObjectName("watrbodyLB")
        self.gridLayout_5.addWidget(self.watrbodyLB, 7, 0, 1, 1)
        self.waterbodyLE = QtWidgets.QLineEdit(self.vectorDataTW)
        self.waterbodyLE.setObjectName("waterbodyLE")
        self.gridLayout_5.addWidget(self.waterbodyLE, 7, 2, 1, 1)
        self.saveWaterbodyTB = QtWidgets.QToolButton(self.vectorDataTW)
        self.saveWaterbodyTB.setObjectName("saveWaterbodyTB")
        self.gridLayout_5.addWidget(self.saveWaterbodyTB, 8, 4, 1, 1)
        self.saveHealthFacilBrowseTB = QtWidgets.QToolButton(self.vectorDataTW)
        self.saveHealthFacilBrowseTB.setObjectName("saveHealthFacilBrowseTB")
        self.gridLayout_5.addWidget(self.saveHealthFacilBrowseTB, 1, 4, 1, 1)
        self.saveProtectedAreaTB = QtWidgets.QToolButton(self.vectorDataTW)
        self.saveProtectedAreaTB.setObjectName("saveProtectedAreaTB")
        self.gridLayout_5.addWidget(self.saveProtectedAreaTB, 10, 4, 1, 1)
        self.riverLE = QtWidgets.QLineEdit(self.vectorDataTW)
        self.riverLE.setObjectName("riverLE")
        self.gridLayout_5.addWidget(self.riverLE, 5, 2, 1, 1)
        self.saveProtectAreaLE = QtWidgets.QLineEdit(self.vectorDataTW)
        self.saveProtectAreaLE.setObjectName("saveProtectAreaLE")
        self.gridLayout_5.addWidget(self.saveProtectAreaLE, 10, 2, 1, 1)
        self.saveRoadsTB = QtWidgets.QToolButton(self.vectorDataTW)
        self.saveRoadsTB.setObjectName("saveRoadsTB")
        self.gridLayout_5.addWidget(self.saveRoadsTB, 4, 4, 1, 1)
        self.saveRiverTB = QtWidgets.QToolButton(self.vectorDataTW)
        self.saveRiverTB.setObjectName("saveRiverTB")
        self.gridLayout_5.addWidget(self.saveRiverTB, 6, 4, 1, 1)
        self.saveHealthFacilPB = QtWidgets.QPushButton(self.vectorDataTW)
        self.saveHealthFacilPB.setObjectName("saveHealthFacilPB")
        self.gridLayout_5.addWidget(self.saveHealthFacilPB, 1, 0, 1, 1)
        self.roadFileLE = QtWidgets.QLineEdit(self.vectorDataTW)
        self.roadFileLE.setObjectName("roadFileLE")
        self.gridLayout_5.addWidget(self.roadFileLE, 2, 2, 1, 1)
        self.roadFileBrowseTB = QtWidgets.QToolButton(self.vectorDataTW)
        self.roadFileBrowseTB.setObjectName("roadFileBrowseTB")
        self.gridLayout_5.addWidget(self.roadFileBrowseTB, 2, 4, 1, 1)
        self.saveRoadPB = QtWidgets.QPushButton(self.vectorDataTW)
        self.saveRoadPB.setObjectName("saveRoadPB")
        self.gridLayout_5.addWidget(self.saveRoadPB, 4, 0, 1, 1)
        self.saveRiverPB = QtWidgets.QPushButton(self.vectorDataTW)
        self.saveRiverPB.setObjectName("saveRiverPB")
        self.gridLayout_5.addWidget(self.saveRiverPB, 6, 0, 1, 1)
        self.saveWaterbodyPB = QtWidgets.QPushButton(self.vectorDataTW)
        self.saveWaterbodyPB.setObjectName("saveWaterbodyPB")
        self.gridLayout_5.addWidget(self.saveWaterbodyPB, 8, 0, 1, 1)
        self.saveProtectAreaPB = QtWidgets.QPushButton(self.vectorDataTW)
        self.saveProtectAreaPB.setObjectName("saveProtectAreaPB")
        self.gridLayout_5.addWidget(self.saveProtectAreaPB, 10, 0, 1, 1)
        self.tabWidget.addTab(self.vectorDataTW, "")
        self.rasterDataTW = QtWidgets.QWidget()
        self.rasterDataTW.setObjectName("rasterDataTW")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.rasterDataTW)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.landuseBrowseTB = QtWidgets.QToolButton(self.rasterDataTW)
        self.landuseBrowseTB.setObjectName("landuseBrowseTB")
        self.gridLayout_2.addWidget(self.landuseBrowseTB, 2, 3, 1, 1)
        self.landuseLE = QtWidgets.QLineEdit(self.rasterDataTW)
        self.landuseLE.setObjectName("landuseLE")
        self.gridLayout_2.addWidget(self.landuseLE, 2, 2, 1, 1)
        self.LanduseLB = QtWidgets.QLabel(self.rasterDataTW)
        self.LanduseLB.setObjectName("LanduseLB")
        self.gridLayout_2.addWidget(self.LanduseLB, 2, 0, 1, 1)
        self.populationFileLE = QtWidgets.QLineEdit(self.rasterDataTW)
        self.populationFileLE.setObjectName("populationFileLE")
        self.gridLayout_2.addWidget(self.populationFileLE, 0, 2, 1, 1)
        self.popSaveLE = QtWidgets.QLineEdit(self.rasterDataTW)
        self.popSaveLE.setObjectName("popSaveLE")
        self.gridLayout_2.addWidget(self.popSaveLE, 1, 2, 1, 1)
        self.populationBrowseTB = QtWidgets.QToolButton(self.rasterDataTW)
        self.populationBrowseTB.setObjectName("populationBrowseTB")
        self.gridLayout_2.addWidget(self.populationBrowseTB, 0, 3, 1, 1)
        self.elevationLE = QtWidgets.QLineEdit(self.rasterDataTW)
        self.elevationLE.setObjectName("elevationLE")
        self.gridLayout_2.addWidget(self.elevationLE, 4, 2, 1, 1)
        self.populationLB = QtWidgets.QLabel(self.rasterDataTW)
        self.populationLB.setObjectName("populationLB")
        self.gridLayout_2.addWidget(self.populationLB, 0, 0, 1, 1)
        self.elevationLB = QtWidgets.QLabel(self.rasterDataTW)
        self.elevationLB.setObjectName("elevationLB")
        self.gridLayout_2.addWidget(self.elevationLB, 4, 0, 1, 1)
        self.popSaveBrowseTB = QtWidgets.QToolButton(self.rasterDataTW)
        self.popSaveBrowseTB.setObjectName("popSaveBrowseTB")
        self.gridLayout_2.addWidget(self.popSaveBrowseTB, 1, 3, 1, 1)
        self.elevationBrowseTB = QtWidgets.QToolButton(self.rasterDataTW)
        self.elevationBrowseTB.setObjectName("elevationBrowseTB")
        self.gridLayout_2.addWidget(self.elevationBrowseTB, 4, 3, 1, 1)
        self.landuseSaveLE = QtWidgets.QLineEdit(self.rasterDataTW)
        self.landuseSaveLE.setObjectName("landuseSaveLE")
        self.gridLayout_2.addWidget(self.landuseSaveLE, 3, 2, 1, 1)
        self.elevationSaveLE = QtWidgets.QLineEdit(self.rasterDataTW)
        self.elevationSaveLE.setObjectName("elevationSaveLE")
        self.gridLayout_2.addWidget(self.elevationSaveLE, 5, 2, 1, 1)
        self.landuseSaveBrowseTB = QtWidgets.QToolButton(self.rasterDataTW)
        self.landuseSaveBrowseTB.setObjectName("landuseSaveBrowseTB")
        self.gridLayout_2.addWidget(self.landuseSaveBrowseTB, 3, 3, 1, 1)
        self.elevationSaveBrowseTB = QtWidgets.QToolButton(self.rasterDataTW)
        self.elevationSaveBrowseTB.setObjectName("elevationSaveBrowseTB")
        self.gridLayout_2.addWidget(self.elevationSaveBrowseTB, 5, 3, 1, 1)
        self.savePopPB = QtWidgets.QPushButton(self.rasterDataTW)
        self.savePopPB.setObjectName("savePopPB")
        self.gridLayout_2.addWidget(self.savePopPB, 1, 0, 1, 1)
        self.saveLandusePB = QtWidgets.QPushButton(self.rasterDataTW)
        self.saveLandusePB.setObjectName("saveLandusePB")
        self.gridLayout_2.addWidget(self.saveLandusePB, 3, 0, 1, 1)
        self.saveElevationPB = QtWidgets.QPushButton(self.rasterDataTW)
        self.saveElevationPB.setObjectName("saveElevationPB")
        self.gridLayout_2.addWidget(self.saveElevationPB, 5, 0, 1, 1)
        self.tabWidget.addTab(self.rasterDataTW, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.groupBox_7)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setToolTip("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.clipFtBrowseTB = QtWidgets.QToolButton(self.groupBox_3)
        self.clipFtBrowseTB.setObjectName("clipFtBrowseTB")
        self.gridLayout_3.addWidget(self.clipFtBrowseTB, 0, 4, 1, 1)
        self.targetClipFtCB = QtWidgets.QComboBox(self.groupBox_3)
        self.targetClipFtCB.setObjectName("targetClipFtCB")
        self.gridLayout_3.addWidget(self.targetClipFtCB, 2, 2, 1, 1)
        self.selectFieldNameCB = QtWidgets.QComboBox(self.groupBox_3)
        self.selectFieldNameCB.setObjectName("selectFieldNameCB")
        self.gridLayout_3.addWidget(self.selectFieldNameCB, 1, 2, 1, 1)
        self.inputClipFtLE = QtWidgets.QLineEdit(self.groupBox_3)
        self.inputClipFtLE.setObjectName("inputClipFtLE")
        self.gridLayout_3.addWidget(self.inputClipFtLE, 0, 2, 1, 1)
        self.inputClipFtLB = QtWidgets.QLabel(self.groupBox_3)
        self.inputClipFtLB.setObjectName("inputClipFtLB")
        self.gridLayout_3.addWidget(self.inputClipFtLB, 0, 0, 1, 1)
        self.selectFieldLB = QtWidgets.QLabel(self.groupBox_3)
        self.selectFieldLB.setObjectName("selectFieldLB")
        self.gridLayout_3.addWidget(self.selectFieldLB, 1, 0, 1, 1)
        self.targetClipFtListLB = QtWidgets.QLabel(self.groupBox_3)
        self.targetClipFtListLB.setObjectName("targetClipFtListLB")
        self.gridLayout_3.addWidget(self.targetClipFtListLB, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 5, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName("gridLayout")
        self.selectPrjRB = QtWidgets.QRadioButton(self.groupBox_4)
        self.selectPrjRB.setObjectName("selectPrjRB")
        self.gridLayout.addWidget(self.selectPrjRB, 1, 1, 1, 1)
        self.selectPrjCB = QtWidgets.QComboBox(self.groupBox_4)
        self.selectPrjCB.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectPrjCB.sizePolicy().hasHeightForWidth())
        self.selectPrjCB.setSizePolicy(sizePolicy)
        self.selectPrjCB.setObjectName("selectPrjCB")
        self.gridLayout.addWidget(self.selectPrjCB, 1, 2, 1, 1)
        self.runReprojectClipPB = QtWidgets.QPushButton(self.groupBox_4)
        self.runReprojectClipPB.setStyleSheet("background-color: rgb(234, 251, 255);")
        self.runReprojectClipPB.setObjectName("runReprojectClipPB")
        self.gridLayout.addWidget(self.runReprojectClipPB, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.listPrjLW = QtWidgets.QListWidget(self.groupBox_5)
        self.listPrjLW.setObjectName("listPrjLW")
        self.gridLayout_4.addWidget(self.listPrjLW, 0, 0, 1, 1)
        # my own addition
        self.accessModLink = QtWidgets.QLabel('<a href="https://www.accessmod.org/">Visit AccessMod Website</a>')
        self.accessModLink.setOpenExternalLinks(True) # Make the link clickable
        self.gridLayout_4.addWidget(self.accessModLink, 1, 0, 1, 1)
        # my own logo
        self.logoLabel = QtWidgets.QLabel(self.groupBox_5)
        pixmap = QtGui.QPixmap(r"..\Images\KEMRI-logo.png")  # path to image file
        scaledPixmap = pixmap.scaled(200, 200, QtCore.Qt.KeepAspectRatio)  # Adjust the width and height as needed
        self.logoLabel.setPixmap(scaledPixmap)
        self.gridLayout_4.addWidget(self.logoLabel, 1, 1, 1, 1)
        self.clearSelectionPB = QtWidgets.QPushButton(self.groupBox_5)
        self.clearSelectionPB.setObjectName("clearSelectionPB")
        self.gridLayout_4.addWidget(self.clearSelectionPB, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AccessMod 5 Data Input Creator By: Bibian Robert"))
        MainWindow.setToolTip(_translate("MainWindow", "This app prepares data inputs need for accessibility modelling in AccessMod"))
        self.groupBox_7.setToolTip(_translate("MainWindow", "Add input features"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Add Features"))
        self.protectedAreaBrowseTB.setText(_translate("MainWindow", "..."))
        self.roadLB.setText(_translate("MainWindow", "Roads: "))
        self.healthFacilLB.setText(_translate("MainWindow", "Health facilities:"))
        self.healthFacilBrowseTB.setText(_translate("MainWindow", "..."))
        self.waterbodyBrowseTB.setText(_translate("MainWindow", "..."))
        self.riverLB.setText(_translate("MainWindow", "River:"))
        self.protectedAreaLB.setText(_translate("MainWindow", "Protected area:"))
        self.riverBrowseTB.setText(_translate("MainWindow", "..."))
        self.watrbodyLB.setText(_translate("MainWindow", "Water body:"))
        self.saveWaterbodyTB.setText(_translate("MainWindow", "..."))
        self.saveHealthFacilBrowseTB.setText(_translate("MainWindow", "..."))
        self.saveProtectedAreaTB.setText(_translate("MainWindow", "..."))
        self.saveRoadsTB.setText(_translate("MainWindow", "..."))
        self.saveRiverTB.setText(_translate("MainWindow", "..."))
        self.saveHealthFacilPB.setText(_translate("MainWindow", "Save File..."))
        self.roadFileBrowseTB.setText(_translate("MainWindow", "..."))
        self.saveRoadPB.setText(_translate("MainWindow", "Save File..."))
        self.saveRiverPB.setText(_translate("MainWindow", "Save File..."))
        self.saveWaterbodyPB.setText(_translate("MainWindow", "Save File..."))
        self.saveProtectAreaPB.setText(_translate("MainWindow", "Save File..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.vectorDataTW), _translate("MainWindow", "Vector Data"))
        self.landuseBrowseTB.setText(_translate("MainWindow", "..."))
        self.LanduseLB.setText(_translate("MainWindow", "Land Use:"))
        self.populationBrowseTB.setText(_translate("MainWindow", "..."))
        self.populationLB.setText(_translate("MainWindow", "Population:"))
        self.elevationLB.setText(_translate("MainWindow", "Elevation:"))
        self.popSaveBrowseTB.setText(_translate("MainWindow", "..."))
        self.elevationBrowseTB.setText(_translate("MainWindow", "..."))
        self.landuseSaveBrowseTB.setText(_translate("MainWindow", "..."))
        self.elevationSaveBrowseTB.setText(_translate("MainWindow", "..."))
        self.savePopPB.setText(_translate("MainWindow", "Save File..."))
        self.saveLandusePB.setText(_translate("MainWindow", "Save File..."))
        self.saveElevationPB.setText(_translate("MainWindow", "Save File..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rasterDataTW), _translate("MainWindow", "Raster Data"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Clip Feature"))
        self.clipFtBrowseTB.setText(_translate("MainWindow", "..."))
        self.targetClipFtCB.setToolTip(_translate("MainWindow", "Select target clip feature from the list"))
        self.inputClipFtLE.setToolTip(_translate("MainWindow", "Select clip feature"))
        self.inputClipFtLB.setText(_translate("MainWindow", "Input Clip Feature:"))
        self.selectFieldLB.setText(_translate("MainWindow", "Select Field Name:"))
        self.targetClipFtListLB.setText(_translate("MainWindow", "Target Clip Feature:"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Reproject and Clip"))
        self.selectPrjRB.setToolTip(_translate("MainWindow", "Check to list projected SRS"))
        self.selectPrjRB.setText(_translate("MainWindow", "Select Projection:"))
        self.selectPrjCB.setToolTip(_translate("MainWindow", "Select projected SRS from the list"))
        self.runReprojectClipPB.setToolTip(_translate("MainWindow", "Click to clip and reproject all input files"))
        self.runReprojectClipPB.setText(_translate("MainWindow", "Reproject and Clip"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Confirm Projected Spatial Reference"))
        self.clearSelectionPB.setToolTip(_translate("MainWindow", "Click to confirm all clipped files have been projected correctly"))
        self.clearSelectionPB.setText(_translate("MainWindow", "Confirm Projected SRS"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setToolTip(_translate("MainWindow", "Exit the program"))

